feat(locale): 国际化新增俄语支持
Tencent/tdesign-mobile-vue pull request #1257
Opened 2024-03-11 09:07 UTC by dexterBo

feat #1249

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2024-03-15 03:49 UTC, anlyyao requested changes

2024-03-15 03:49 UTC, anlyyao commented on src/locale/ru.ts
> +    format: 'DD-MM-YYYY',
好像应该是 DD.MM.YYYY 🤔，辛苦这里再确认一下哈～

2024-03-15 03:54 UTC, dexterBo commented on src/locale/ru.ts
> +    format: 'DD-MM-YYYY',
是的，我修改一下

2024-03-15 03:55 UTC, dexterBo commented on src/locale/ru.ts
> +    format: 'DD-MM-YYYY',
已经修改了

2024-03-20 02:47 UTC, anlyyao approved these changes

2024-03-20 02:47 UTC, merged