feat(loacale): language-it
Tencent/tdesign-mobile-vue pull request #1263
Opened 2024-03-12 09:27 UTC by catiwang

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

fix #1253

### 💡 需求背景和解决方案

### 📝 更新日志

- feat(Locale): 新增意大利语言包

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2024-03-12 09:51 UTC, catiwang commented
@anlyyao dateTimePicker的format有问过意大利那边，习惯写法是用DD-MM-YYYY，如果需要修改，可以再跟我说～

2024-03-13 11:43 UTC, anlyyao commented
> @anlyyao dateTimePicker的format有问过意大利那边，习惯写法是用DD-MM-YYYY，如果需要修改，可以再跟我说～
okkkk，顺便确认一下这里的拼写问题～
<img width="560" alt="截屏2024-03-13 19 43 01" src="https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/094314e4-7c97-4bd8-aae8-681e26dc5b98">

2024-03-14 02:27 UTC, catiwang commented
@anlyyao 这个单词的小写直译就是对应的英文next这个单词，可能大写识别错误了😂

2024-03-14 02:32 UTC, anlyyao commented
> @anlyyao 这个单词的小写直译就是对应的英文next这个单词，可能大写识别错误了😂

🤔 那要在 typos-config.toml 配置中加一下 `Successivo = "Successivo"`

2024-03-15 03:26 UTC, anlyyao requested changes

2024-03-15 03:26 UTC, anlyyao commented on src/locale/it-it.ts
> +    format: 'DD-MM-YYYY',
确认了要使用 DD-MM-YYYY， 👍

2024-03-20 02:53 UTC, anlyyao approved these changes

2024-03-20 02:54 UTC, merged