feat(fab): update api && align design
Tencent/tdesign-mobile-vue pull request #182
Opened 2022-06-15 07:04 UTC by anlyyao

### 🤔 这个 PR 的性质是？
- [x] 新特性提交
- [x] 文档改进
- [x] 演示代码改进

### 🔗 相关 Issue
#154 
#155 

### 📝 更新日志
- feat(fab): 新增buttonProps和style属性，demo对齐视觉稿

2022-06-17 11:01 UTC, LeeJim requested changes

2022-06-18 03:50 UTC, LeeJim commented
需要改的是代码，而不是文档 :(

2022-06-20 03:12 UTC, anlyyao commented
> 需要改的是代码，而不是文档 :(

文档是新拉的～～ 有啥子问题嚒 😳

2022-06-20 12:46 UTC, LeeJim commented on src/fab/fab.vue
> +  <t-button
需要透传 button 的所有 props

2022-06-21 02:34 UTC, merged