Oyx/feat/toast/props
Tencent/tdesign-mobile-vue pull request #204
Opened 2022-06-28 03:36 UTC by oceanlvr

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

#176 

### 💡 需求背景和解决方案

补充 Toast overlayProps、showOverlay 属性

### 📝 更新日志

- feat(Toast): 补充 overlayProps 支持透传 overlay 属性，支持 showOverlay 遮罩

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-06-30 02:43 UTC, LeeJim commented on src/toast/toast.vue
> +      () => props.preventScrollThrough || (props.showOverlay && props.preventScrollThrough !== false),
这个值感觉不太对，不应该是 showOverlay 的时候也阻止滚动，因为 overlay 也有 preventScrollThrough 的配置

2022-06-30 02:45 UTC, LeeJim requested changes

2022-06-30 02:45 UTC, LeeJim commented on src/toast/toast.vue
> +      () => props.preventScrollThrough || (props.showOverlay && props.preventScrollThrough !== false),
这个值感觉不太对，showOverlay 的时候不应该也阻止屏幕滚动，因为 overlay 也有这个配置

2022-07-04 03:01 UTC, oceanlvr commented on src/toast/toast.vue
> +      () => props.preventScrollThrough || (props.showOverlay && props.preventScrollThrough !== false),
收到🫡，找了下 overlay 这个配置目前不可透传，我应该暴露 overlay 的阻止屏幕属性吗？

2022-07-06 09:04 UTC, LeeJim requested changes

2022-07-06 09:04 UTC, LeeJim commented on src/toast/toast.vue
> +      props.preventScrollThrough && document.body.classList.remove(preventScrollCls);
preventScrollThrough 应该是由 overlay 来处理的，因此我重构了下 overlay。
可以合并下 develop 重新修改下

2022-07-10 05:22 UTC, LeeJim requested changes

2022-07-10 05:22 UTC, LeeJim commented on src/overlay/overlay.vue
> +
这部分可以移除，已经在 overlay 增加了 touchmove 事件来实现禁止屏幕滚动，不需要额外实现了

2022-07-10 16:45 UTC, oceanlvr commented on src/overlay/overlay.vue
> +
overlay 组件在删除这几行后会导致 overlay 禁止屏幕滚动失效，

2022-07-11 15:56 UTC, LeeJim commented on src/overlay/overlay.vue
> +import { computed, defineComponent, onMounted, onUnmounted } from 'vue';
这两个方法应该也是没有用到的

2022-07-12 02:52 UTC, oceanlvr commented on src/overlay/overlay.vue
> +import { computed, defineComponent, onMounted, onUnmounted } from 'vue';
十分抱歉，删除了无用的导入

2022-07-12 05:48 UTC, LeeJim approved these changes

2022-07-12 05:48 UTC, merged