feat(Result): complete result components
Tencent/tdesign-mobile-vue pull request #243
Opened 2022-07-19 01:42 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 新特性提交

### 📝 更新日志

- feat(Result): 新增组件

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-07-21 04:01 UTC, LeeJim commented
代码冲突了；CI 也挂了

2022-07-25 04:34 UTC, LeeJim requested changes

2022-07-25 04:34 UTC, LeeJim commented on site/docs.config.js
> +          title: 'Loading 加载中',
冲突解决错了。多了个 loading

2022-07-25 04:34 UTC, LeeJim commented on src/result/demos/custom.vue
> +  height: 80px;
不要设置高度了，变形了

2022-07-25 04:34 UTC, LeeJim commented on src/result/result.vue
> +        <img v-if="typeof image === 'string'" :src="image" />
是不是可以用 t-image 组件。
顺便加上 imageProps

2022-07-25 07:41 UTC, anlyyao commented on site/docs.config.js
> +          title: 'Loading 加载中',
已处理～

2022-07-25 07:42 UTC, anlyyao commented on src/result/result.vue
> +        <img v-if="typeof image === 'string'" :src="image" />
已加上～

2022-07-25 07:42 UTC, anlyyao commented on src/result/demos/custom.vue
> +  height: 80px;
是填充模式的问题～ 已解决

2022-07-25 07:51 UTC, LeeJim commented on src/result/demos/custom.vue
> +  height: 80px;
这个高度也移除了吧。看起来就很奇怪

2022-07-25 11:48 UTC, LeeJim approved these changes
LGTM

2022-07-25 11:48 UTC, merged