fix(countdown): fix miliseconds problem
Tencent/tdesign-mobile-vue pull request #313
Opened 2022-08-26 08:34 UTC by TingShine

fix #312

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

[毫秒级渲染配置无效](https://github.com/Tencent/tdesign-mobile-vue/issues/312)

### 💡 需求背景和解决方案

props传入milisecond为true无效

### 📝 更新日志

- fix(countdown): 修复milisecond配置无效的问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-08-29 09:00 UTC, anlyyao commented
@TingShine 辛苦合一下 dev 分支，重跑一下 ci～

2022-09-06 11:57 UTC, anlyyao commented
补充一下徽标即可～

2022-09-16 08:07 UTC, LeeJim requested changes
存在两个问题。
1 一个 PR 里有两个组件的单测，需要拆分，分别提交
2 git 分支有问题，diff 有问题，提交了 script 的代码

2022-09-20 08:33 UTC, LeeJim approved these changes

2022-09-20 08:34 UTC, merged