test: add tabbar test
Tencent/tdesign-mobile-vue pull request #314
Opened 2022-08-26 08:40 UTC by HelKyle

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [x] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

#271 

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [x] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-09-08 03:11 UTC, anlyyao commented
icon类型是Slot / Function， 可以用

import { AppIcon as TIconApp } from 'tdesign-icons-vue-next';
const icon = () =>

的方式引用～

2022-09-08 03:11 UTC, anlyyao commented
没有生成徽标～ npm run update:coverage-badge

2022-09-08 03:48 UTC, anlyyao approved these changes

2022-09-16 07:52 UTC, LeeJim requested changes

2022-09-16 07:52 UTC, LeeJim commented on src/tab-bar/__test__/index.test.jsx
> +      const onChange = vi.fn()
这个 onChange 不需要 mock，直接定义函数即可

2022-09-16 07:52 UTC, LeeJim commented on src/tab-bar/__test__/index.test.jsx
> +            onChange={onChange}
这里定义了 v-model 就不需要在 onchange 里修改 value 的值

2022-09-18 10:44 UTC, LeeJim approved these changes

2022-09-18 10:44 UTC, merged