test(upload): add unit test for upload
Tencent/tdesign-mobile-vue pull request #318
Opened 2022-08-27 13:36 UTC by palmcivet

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [x] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

[tdesign-mobile-vue#271](https://github.com/Tencent/tdesign-mobile-vue/issues/271)

### 💡 需求背景和解决方案

### 📝 更新日志

- feat(upload): 新增单元测试
- fix(upload): 修复上传失败后，再次上传会产生报错的问题

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-08-29 08:59 UTC, anlyyao commented
@palmcivet 辛苦合一下 dev 分支，重跑一下 ci～

2022-09-06 10:51 UTC, anlyyao commented
@palmcivet  branches覆盖率小于80，可以在补充一下requestMethod的内容～

2022-09-16 08:23 UTC, LeeJim approved these changes

2022-09-16 08:24 UTC, LeeJim commented
单测没过

2022-09-20 07:03 UTC, LeeJim requested changes

2022-09-20 07:03 UTC, LeeJim commented on src/upload/__test__/index.test.jsx
> +        allowUploadDuplicateFile: true,
需要测试一下为 false 的情况

2022-09-21 05:24 UTC, palmcivet commented on src/upload/__test__/index.test.jsx
> +    element.files = [...fileList];
Upload 的 `handleChange()` 后会清空 input 的内容，所以第二次触发其实就是赋值，不会带上之前的内容，不过为了便于理解，优化了一下 mock 函数

2022-09-26 10:01 UTC, LeeJim approved these changes

2022-09-26 10:01 UTC, merged