test: loading test
Tencent/tdesign-mobile-vue pull request #320
Opened 2022-08-28 12:38 UTC by zhangpaopao0609

### 🤔 这个 PR 的性质是？

- [x] 测试用例

### 🔗 相关 Issue

https://github.com/Tencent/tdesign-mobile-vue/issues/271?target=loading

### 💡 需求背景和解决方案

loading 增加测试用例

### 📝 更新日志

- test(Loading): 增加测试用例

- [x] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-09-08 07:26 UTC, anlyyao approved these changes

2022-09-09 09:13 UTC, zhangpaopao0609 commented on src/loading/__test__/index.test.jsx
> +      // 这里是希望获取到元素的样式，但是获取不到，看 issue 中也有类似的问题，这里先保留
快照没有，直接是 color: ''

2022-09-15 11:32 UTC, LeeJim requested changes

2022-09-15 11:32 UTC, LeeJim commented on src/loading/__test__/index.test.jsx
> +      expect(errorBlock.element.innerHTML).toBeTruthy('加载失败');
这里应该是 `toBe('加载失败')`

2022-09-15 11:32 UTC, LeeJim commented on src/loading/__test__/index.test.jsx
> +      expect(wrapper.element).toMatchSnapshot();
判断下 `animation-play-state` 而不是 snapshot

2022-09-15 11:32 UTC, LeeJim commented on src/loading/__test__/index.test.jsx
> +      expect(wrapper.element).toMatchSnapshot();
最好判断下 `animation-direction`

2022-09-15 11:32 UTC, LeeJim commented on src/loading/__test__/index.test.jsx
> +    it(':text', () => {
这个只是判断了是否渲染 `t-loading__text` 这个 DOM，
应该需要传入个 slot 类型的 text 测试一下

2022-09-16 02:57 UTC, zhangpaopao0609 commented on src/loading/__test__/index.test.jsx
> +      expect(errorBlock.element.innerHTML).toBeTruthy('加载失败');
1

2022-09-16 07:47 UTC, LeeJim commented on src/loading/__test__/index.test.jsx
> +      const custonLoading = 'custon-loading-text'
拼写错误，应该是 customLoading

2022-09-20 08:29 UTC, LeeJim approved these changes

2022-09-20 08:34 UTC, merged