test: add test for sticky
Tencent/tdesign-mobile-vue pull request #348
Opened 2022-09-12 14:26 UTC by 4xii

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-09-12 14:33 UTC, 4xii commented
#271

2022-09-27 09:17 UTC, LeeJim requested changes

2022-09-27 09:17 UTC, LeeJim commented on src/sticky/__test__/index.test.jsx
> +      expect(vm.onScrollParam).toEqual({
不需要这样另外赋值，直接使用 toHaveBeenCalledWith

2022-09-28 02:03 UTC, 4xii commented on src/sticky/__test__/index.test.jsx
> +      const mockStickyRect = vi.spyOn(wrapper.find('.t-sticky').element, 'getBoundingClientRect').mockReturnValue({
这个和下面的toHaveBeenCalledWith我再改改

2022-09-28 02:55 UTC, 4xii commented on src/sticky/__test__/index.test.jsx
> +    it(': disabled', async () => {
已删

2022-10-09 03:21 UTC, LeeJim requested changes

2022-10-09 03:21 UTC, LeeJim commented on src/sticky/__test__/index.test.jsx
> +const TRUTH = 'expect(meimei === 4xi lover).toBe(true)';
这里好像是多余的，而且开源项目的代码是严肃的。

2022-10-09 03:21 UTC, LeeJim commented on src/shared/useTest/index.ts
> +export function useVitest(vi: typeof import('vitest')['vitest']) {
这个抽象出来的函数好像没有太多意义，可以不抽象的

2022-10-09 03:21 UTC, LeeJim commented on src/shared/useTest/index.ts
> +import sleep from 'lodash';
这是OK的？

2022-10-09 03:21 UTC, LeeJim commented on src/sticky/__test__/index.test.jsx
> +      await makeScroll(document.documentElement, 'scrollTop', 10);
这里直接使用 window 不就好了，为啥要在函数里做转换？

2022-10-09 03:21 UTC, LeeJim commented on src/sticky/__test__/index.test.jsx
> +      expect(onScrollParameterFn).toHaveBeenCalledWith(true);
这里怎么可以连续使用相反的值都通过测试？

2022-10-09 04:41 UTC, 4xii commented on src/sticky/__test__/index.test.jsx
> +      await makeScroll(document.documentElement, 'scrollTop', 10);
写了个makeScroll方法，这个方法相对于直接调用window会更加灵活，别的地方可以复用。

2022-10-09 04:46 UTC, 4xii commented on src/sticky/__test__/index.test.jsx
> +      expect(onScrollParameterFn).toHaveBeenCalledWith(true);
这不是连续使用，这是测试两次调用的结果。toHaveBeenCalledWith只要写在执行方法之后，结果都是一样的。介意的话我可以调整一下位置，区别不大。

2022-10-09 04:46 UTC, 4xii commented on src/sticky/__test__/index.test.jsx
> +const TRUTH = 'expect(meimei === 4xi lover).toBe(true)';
ok

2022-10-20 08:38 UTC, LeeJim approved these changes

2022-10-20 08:44 UTC, merged