test: add unit test for swipe-cell
Tencent/tdesign-mobile-vue pull request #360
Opened 2022-09-20 02:36 UTC by anlyyao

### 🤔 这个 PR 的性质是？
- [x] 测试用例

### 📝 更新日志

- feat(SwipeCell): 新增单元测试

2022-09-20 08:09 UTC, LeeJim requested changes

2022-09-20 08:09 UTC, LeeJim commented on src/swipe-cell/__test__/index.test.jsx
> +      expect(SwipeDirection).toBe(undefined);
这里可以使用 toHaveBeenCalledWith 来代替，就不需要重新声明个新变量了

2022-09-20 08:09 UTC, LeeJim commented on src/swipe-cell/__test__/index.test.jsx
> +      right.map(async (item, index)=> {
这里应该使用 forEach 而不是 map

2022-09-20 08:09 UTC, LeeJim commented on src/swipe-cell/__test__/index.test.jsx
> +      expect(SwipeDirection).toBe('right');
同上

2022-09-20 08:35 UTC, anlyyao commented on src/swipe-cell/__test__/index.test.jsx
> +      expect(SwipeDirection).toBe(undefined);
1

2022-09-20 08:35 UTC, anlyyao commented on src/swipe-cell/__test__/index.test.jsx
> +      right.map(async (item, index)=> {
1

2022-09-20 08:35 UTC, anlyyao commented on src/swipe-cell/__test__/index.test.jsx
> +      expect(SwipeDirection).toBe('right');
1

2022-09-27 07:50 UTC, LeeJim approved these changes

2022-09-27 07:50 UTC, merged