Refactor/navbar: 重构NavBar组件
Tencent/tdesign-mobile-vue pull request #391
Opened 2022-10-10 02:24 UTC by TingShine

#347 

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [x] 文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [x] 重构
- [ ] 代码风格优化
- [x] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

[navbar重构](https://github.com/Tencent/tdesign-mobile-vue/issues/347)

### 💡 需求背景和解决方案

组件API文档不规范，需要重新生成文档，重构组件

### 📝 更新日志

- refactor(navbar): 重构组件，包括API、文档和交互

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-10-10 08:13 UTC, anlyyao commented
收到～ 我来处理一下ci

2022-10-21 07:31 UTC, LeeJim requested changes

2022-10-21 07:31 UTC, LeeJim commented on src/navbar/demos/mobile.vue
> +      <t-navbar title="标题" left-icon :fixed="false" @left-click="handleClick"> </t-navbar>
这里直接用 demos/base.vue 即可，这样保证了展示的代码和演示示例一致。
下面同理，mobile.vue 不要有示例代码

2022-10-21 07:31 UTC, LeeJim commented on src/navbar/navbar.md
> +animation | Boolean | true | 是否添加动画效果 | N
属性还没支持，需要在说明里添加【开发中】

2022-10-21 07:31 UTC, LeeJim commented on src/navbar/navbar.md
> +homeIcon | Boolean / Slot / Function | - | 首页图标。值为 true 表示显示默认返回图标，值为 false 表示不显示首页图标，值为其他表示自定义图标。TS 类型：`boolean | TNode`。[通用类型定义](https://github.com/Tencent/tdesign-mobile-vue/blob/develop/src/commo
home可以移除了，保留 left 即可

2022-10-21 07:31 UTC, LeeJim commented on src/navbar/navbar.md
> +onLeftClick | Function |  | TS 类型：`() => void`<br/>点击左边按钮时触发 | N
缺少了 onRightClick

2022-10-21 07:31 UTC, LeeJim commented on src/navbar/navbar.vue
>      const handleBack = () => {
其实是 left-icon 语义上不要限定就是 back

2022-10-21 07:31 UTC, LeeJim commented on src/navbar/navbar.vue
> +        `position: ${fixed.value ? 'fixed' : 'relative'}; top: 0; left: 0; width: 100%; background: ${
其他默认的样式，就写到 less 里吧

2022-10-31 09:33 UTC, anlyyao commented
@TingShine  辛苦这里在跟进一下～

2022-11-03 08:53 UTC, LeeJim approved these changes

2022-11-03 08:53 UTC, merged