test(DateTimePicker): add unit test for date-time-picker
Tencent/tdesign-mobile-vue pull request #407
Opened 2022-10-13 08:17 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2022-10-18 10:20 UTC, LeeJim requested changes

2022-10-18 10:20 UTC, LeeJim commented on src/date-time-picker/__test__/index.test.jsx
> +const currentDate = new Date();
不确定日期的话，每一天的日期都不一样，可能会导致单测每天都挂掉

2022-10-20 02:26 UTC, anlyyao commented on src/date-time-picker/__test__/index.test.jsx
> +const currentDate = new Date();
1

目前develop分支的该组件demo快照也挂了，也将demo的日期固定，并移除了无用代码

2022-10-20 06:42 UTC, LeeJim approved these changes

2022-10-20 06:43 UTC, merged