test(indexes): 新增 indexes 单元测试
Tencent/tdesign-mobile-vue pull request #418
Opened 2022-10-20 02:17 UTC by byq1213

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [x] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- test(indexes): 新增 indexes 单元测试
- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-10-20 08:27 UTC, LeeJim requested changes

2022-10-20 08:27 UTC, LeeJim commented on src/indexes/__test__/index.test.tsx
> +      expect(log).toHaveBeenCalled(); // 检查是否被调用
将 onSelect 定义成 jest.fn，然后直接使用 toHaveBeenCalledWith 即可，不要绕弯

2022-10-20 08:27 UTC, LeeJim commented on src/indexes/indexes.vue
> +      targets[0].scrollIntoView && targets[0]?.scrollIntoView();
可以改成 `targets[0]?.scrollIntoView?.();`

2022-10-24 03:28 UTC, LeeJim commented
分支有问题，diff错乱了。
麻烦重新提个PR吧，参考这个文档：https://github.com/Tencent/tdesign/blob/main/docs/contributing.md

2022-10-24 03:28 UTC, closed without merging

2022-10-24 10:25 UTC, byq1213 commented
> 

已重新PR
https://github.com/Tencent/tdesign-mobile-vue/pull/425