fix(Tag): update style
Tencent/tdesign-mobile-vue pull request #507
Opened 2023-03-01 08:30 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- feat(Tag):  支持 css variable

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-03-03 06:11 UTC, anlyyao commented
@LeeJim  目前流水线上build失败应该是原dev分支问题，不是这条pr的问题～

2023-03-10 10:35 UTC, LeeJim requested changes

2023-03-10 10:35 UTC, LeeJim commented on src/back-top/demos/mobile.vue
> +  const { scrollTop } = (e.currentTarget as any)?.scrollingElement || {};
尽量不要使用 any

2023-03-10 10:35 UTC, LeeJim commented on src/calendar/demos/custom-text.vue
> +const format = (day: any) => {
day 的类型在 ts 里有定义，最好 copy 过来

2023-03-10 10:35 UTC, LeeJim commented on src/dropdown-menu/demos/demo-container.vue
> +      const container: any = refContainer.value;
不要用 any

2023-03-10 10:35 UTC, LeeJim commented on src/indexes/demos/base.vue
> +import Toast from '../../toast/index';
原写法是对的

2023-03-10 10:35 UTC, LeeJim commented on src/toast/demos/iconText.vue
> +import Toast from '../index';
使用全局的命令行调用，可以不用引入 toast，下面几个同理

2023-03-10 12:20 UTC, anlyyao commented on src/back-top/demos/mobile.vue
> +  const { scrollTop } = (e.currentTarget as any)?.scrollingElement || {};
1

2023-03-10 12:20 UTC, anlyyao commented on src/dropdown-menu/demos/demo-container.vue
> +      const container: any = refContainer.value;
1

2023-03-10 12:20 UTC, anlyyao commented on src/indexes/demos/base.vue
> +import Toast from '../../toast/index';
1

2023-03-10 12:20 UTC, anlyyao commented on src/toast/demos/iconText.vue
> +import Toast from '../index';
1

2023-03-13 03:12 UTC, LeeJim approved these changes

2023-03-13 03:14 UTC, LeeJim approved these changes

2023-03-13 07:49 UTC, merged