chore(footer): base code
Tencent/tdesign-mobile-vue pull request #525
Opened 2023-03-21 02:08 UTC by mamumu123

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [x] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

https://github.com/Tencent/tdesign-mobile-vue/issues/514?target=footer
### 💡 需求背景和解决方案

1.新增组件 footer
2. ![截屏2023-03-21 10 07 31](https://user-images.githubusercontent.com/19382362/226502887-9cb34b91-616b-4908-b4eb-2388e83f076e.png)
### 📝 更新日志

- feat(footer): 增加组件 footer

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-03-22 06:55 UTC, LeeJim requested changes

2023-03-22 06:55 UTC, LeeJim commented on src/footer/footer.vue
> +        <t-image v-else-if="logo.titleUrl" :src="logo.titleUrl" :class="`${name}__title-url`" />
这个 titleUrl 应该是不存在的。应该是有一个属性叫 `logo.url`。
存在 `logo.url` 的时候。image 是由 a 标签包裹的，`logo.url` 的值赋予 href

2023-03-22 06:55 UTC, LeeJim commented on src/footer/footer.vue
> +import FooterProps from './props';
这个 props 文件是不是没有生成？

2023-03-22 08:13 UTC, mamumu123 commented on src/footer/footer.vue
> +        <t-image v-else-if="logo.titleUrl" :src="logo.titleUrl" :class="`${name}__title-url`" />
@anlyyao 辛苦确认一下？
<img width="519" alt="截屏2023-03-22 16 12 34" src="https://user-images.githubusercontent.com/19382362/226839700-378d3ebb-5742-499a-b564-a93f302bf294.png">

2023-03-22 08:14 UTC, mamumu123 commented on src/footer/footer.vue
> +import FooterProps from './props';
<img width="444" alt="截屏2023-03-22 16 14 19" src="https://user-images.githubusercontent.com/19382362/226840143-8131c081-75eb-435d-a0bf-3eb5fbc95ee8.png">

2023-03-23 05:25 UTC, LeeJim commented on src/footer/footer.vue
> +        <t-image v-else-if="logo.titleUrl" :src="logo.titleUrl" :class="`${name}__title-url`" />
API 已经更新了

2023-03-24 03:31 UTC, LeeJim requested changes

2023-03-24 03:31 UTC, LeeJim commented on src/footer/footer.vue
> +        <t-image v-if="logo.url" :src="logo.url" :class="`${name}__title-url`" />
这一行可以删掉。

2023-03-24 03:31 UTC, merged