refactor(Cascader): new cascader
Tencent/tdesign-mobile-vue pull request #533
Opened 2023-03-27 08:31 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- break(Cascader): 移除cancel、click-tab 事件
- breakCascader): 移除 closeIcon 属性
- featCascader): 新增 close 事件
- featCascader): 新增 closeBtn、keys、subTitles

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-04-04 04:10 UTC, LeeJim commented
示例没更新

2023-04-04 04:11 UTC, LeeJim commented
common 已合并，麻烦更新下

2023-04-04 05:24 UTC, LeeJim requested changes
有两个问题，
- tabs 的下划线没有定位正确
- 带初始值的 radio 没有勾选正确

2023-04-06 03:22 UTC, anlyyao commented
> 有两个问题，
> 
> * tabs 的下划线没有定位正确
> * 带初始值的 radio 没有勾选正确

已处理。

2023-04-10 06:41 UTC, merged