refactor(search): new search
Tencent/tdesign-mobile-vue pull request #540
Opened 2023-03-29 03:57 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [x] 文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- break(Search): 移除 label 属性相关

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-03-29 08:43 UTC, LeeJim commented
#506 这个问题有顺便修复吗？

2023-03-29 12:11 UTC, anlyyao commented
> #506 这个问题有顺便修复吗？

已处理。 可以试试第一个demo示例

2023-04-04 03:17 UTC, LeeJim commented
> > #506 这个问题有顺便修复吗？
> 
> 已处理。 可以试试第一个demo示例

已处理的话，记得关联一下 issue 啊

2023-04-04 03:30 UTC, LeeJim requested changes
center 不生效，其他没问题

2023-04-04 04:23 UTC, LeeJim approved these changes

2023-04-04 04:23 UTC, merged