refactor(rate): rate tips
Tencent/tdesign-mobile-vue pull request #582
Opened 2023-04-11 08:26 UTC by fengchunqi

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [x] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

[移动端 mobile-vue 发布正式版 #514](https://github.com/Tencent/tdesign-mobile-vue/issues/514?target=rate)

### 💡 需求背景和解决方案

### 📝 更新日志

- refactor(rate): rate增加tips

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-04-13 07:01 UTC, LeeJim requested changes
交互上有几个bug：
1. tips偶尔会不消失
2. 半选的情况下，tips里有一个star会慢一点出现

2023-04-19 02:17 UTC, fengchunqi commented on src/rate/demos/base.vue
> +  <CustomCell title="实心评分">
去掉CustomCell后，样式是单独都写在每个示例里面吗？

2023-04-19 02:18 UTC, fengchunqi commented on src/rate/rate.vue
> +import { IconFont } from 'tdesign-icons-vue-next';
现在不是改成传icon name了吗

2023-04-21 08:05 UTC, LeeJim commented on src/rate/demos/base.vue
> +  <CustomCell title="实心评分">
是的。

2023-04-21 08:17 UTC, LeeJim commented on src/rate/rate.vue
> +import { IconFont } from 'tdesign-icons-vue-next';
这里要和小程序不一样。

2023-04-21 08:18 UTC, LeeJim commented
提交的分支也不对，需要合并进 develop

2023-04-26 09:30 UTC, closed without merging