fix(Dialog): resolve demo error
Tencent/tdesign-mobile-vue pull request #682
Opened 2023-05-21 15:08 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(Dialog): 修复示例失效的问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-05-22 03:04 UTC, LeeJim approved these changes

2023-05-22 03:24 UTC, LeeJim requested changes

2023-05-22 03:24 UTC, LeeJim commented on src/dialog/demos/plugin.vue
> -  const $dialog: any = inject('$dialog');
这样 inject 不能用的问题也要跟进处理下

2023-05-23 08:48 UTC, anlyyao commented on src/dialog/demos/plugin.vue
> -  const $dialog: any = inject('$dialog');
1 示例问题，已处理。

2023-05-23 09:58 UTC, LeeJim approved these changes

2023-05-23 09:58 UTC, merged