fix(DropdownMenu): resolve id problem
Tencent/tdesign-mobile-vue pull request #782
Opened 2023-06-01 12:00 UTC by ccccpj

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(DropdownMenu): resolve id problem

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-06-01 15:37 UTC, LeeJim requested changes

2023-06-01 15:37 UTC, LeeJim commented on src/dropdown-menu/dropdown-item.vue
> +    const randomId = Math.random().toString(36).slice(-6);
这里不用随机值，直接从0递增更靠谱

2023-06-02 07:23 UTC, ccccpj commented on src/dropdown-menu/dropdown-item.vue
> +    const randomId = Math.random().toString(36).slice(-6);
这里的问题是 dropdown Item 的 id 重复导致菜单 展开状态控制问题；在单个 dropdown menu 中使用递增的方式可行。
但如果页面中使用了 两个或以上 dropdown menu 时，dropdown menu 间 相对独立，递增会导致多个 id: 0, id: 1.....

2023-06-02 07:24 UTC, ccccpj commented on src/dropdown-menu/dropdown-item.vue
> +    const randomId = Math.random().toString(36).slice(-6);
> 这里不用随机值，直接从0递增更靠谱
这里的问题是 dropdown Item 的 id 重复导致菜单 展开状态控制问题；在单个 dropdown menu 中使用递增的方式可行。
但如果页面中使用了 两个或以上 dropdown menu 时，dropdown menu 间 相对独立，递增会导致多个 id: 0, id: 1.....

2023-06-02 07:24 UTC, ccccpj commented on src/dropdown-menu/dropdown-item.vue
> +    const randomId = Math.random().toString(36).slice(-6);
> 这里不用随机值，直接从0递增更靠谱

这里的问题是 dropdown Item 的 id 重复导致菜单 展开状态控制问题；在单个 dropdown menu 中使用递增的方式可行。
但如果页面中使用了 两个或以上 dropdown menu 时，dropdown menu 间 相对独立，递增会导致多个 id: 0, id: 1.....

2023-06-02 09:05 UTC, LeeJim commented on src/dropdown-menu/dropdown-item.vue
> +    const randomId = Math.random().toString(36).slice(-6);
可以参考小程序的 src/common/utils.ts 的 uniqueFactory 方法

2023-06-02 09:52 UTC, ccccpj commented on src/dropdown-menu/dropdown-item.vue
> +    const randomId = Math.random().toString(36).slice(-6);
> 可以参考小程序的 src/common/utils.ts 的 uniqueFactory 方法

学习了

2023-06-03 03:32 UTC, anlyyao approved these changes

2023-06-05 02:14 UTC, LeeJim approved these changes

2023-06-05 02:14 UTC, merged