build: export reset.css to the dist directory
Tencent/tdesign-mobile-vue pull request #853
Opened 2023-06-10 11:38 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
### 🔗 相关 PR
common： [#1392](https://github.com/Tencent/tdesign-common/pull/1392)

### 💡 需求背景和解决方案
背景： 按官网说明接入tdesign-mobile-vue，部分组件出现样式问题。
原因：缺少 _reset.css文件
方案：将_reset.css 涉及的组件样式，全部迁移至组件本身。同时，单独导出 reset.css 到 dist 目录，支持从  `tdesign-mobile-vue/dist/reset.css` 中单独引入，存在不兼容更新。

### 📝 更新日志

- break: 默认移除全局 `reset.css` 样式引入，可从 `tdesign-mobile-vue/dist/reset.css` 中单独引入

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-06-11 15:34 UTC, LeeJim requested changes

2023-06-11 15:34 UTC, LeeJim commented on site/docs/getting-started.md
> +### 通过插件按需引用使用
这部分可能还不支持，可以找 uyarn 确认一下

2023-06-12 07:24 UTC, anlyyao commented on site/docs/getting-started.md
> +### 通过插件按需引用使用
> 这部分可能还不支持，可以找 uyarn 确认一下

https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/tdesign.ts。插件已包含mobile-vue，已测可用

2023-06-12 10:59 UTC, LeeJim approved these changes

2023-06-12 10:59 UTC, merged