style(ActionSheet): resolved style error
Tencent/tdesign-mobile-vue pull request #854
Opened 2023-06-10 14:19 UTC by anlyyao

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [x] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue
### 🔗 相关 PR
common: https://github.com/Tencent/tdesign-common/pull/1394

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(GridItem): 修复 `Image` 属性不支持 `Function` 类型
- fix(ActionSheet): 修复禁用态背景色错误
- fix(ActionSheet): 修复示例占位图错误

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-06-11 15:32 UTC, LeeJim requested changes

2023-06-11 15:32 UTC, LeeJim commented on src/grid/grid-item.vue
> +      if (isObject(props.image) && !isFunction(props.image) && !context.slots.image) {
image 是支持 function 和 插槽。目前看起来好像不行，应该使用 renderTNode

2023-06-12 07:23 UTC, anlyyao commented on src/grid/grid-item.vue
> +      if (isObject(props.image) && !isFunction(props.image) && !context.slots.image) {
原本就是支持的在line46。iamge模块的支持优先级 String/Object > Funciton/Slot。而原先realImage处理有问题。image为function时，isObject(props.image)是true，所以导致function类型无效、

2023-06-12 07:23 UTC, anlyyao commented on src/grid/grid-item.vue
> +      if (isObject(props.image) && !isFunction(props.image) && !context.slots.image) {
> image 是支持 function 和 插槽。目前看起来好像不行，应该使用 renderTNode

原本就是支持的在line46。iamge模块的支持优先级 String/Object > Funciton/Slot。而原先realImage处理有问题。image为function时，isObject(props.image)是true，所以导致function类型无效、

2023-06-12 08:55 UTC, LeeJim approved these changes

2023-06-12 08:55 UTC, merged