feat: noticeBar组件
Tencent/tdesign-mobile-vue pull request #99
Opened 2022-04-30 02:38 UTC by xia7187

feat: noticeBar组件

2022-05-17 03:17 UTC, LeeJim requested changes

2022-05-17 03:17 UTC, LeeJim commented on src/notice-bar/notice-bar.vue
> +    if ((props.prefixIcon as unknown as string) !== '') {
不要这样写，prefixIcon 没有 string 类型

2022-05-17 03:17 UTC, LeeJim commented on src/notice-bar/notice-bar.vue
> +      computedPrefixIcon = props.prefixIcon
这里也同样不需要判断 props.prefixIcon 是否存在

2022-05-17 03:17 UTC, LeeJim commented on src/notice-bar/notice-bar.vue
> +  info: [h(InfoCircleFilledIcon)],
这里其实是没必要提前 h 好的，可以确定之后再执行

2022-05-17 03:17 UTC, LeeJim commented on src/notice-bar/notice-bar.vue
> +        delay: marquee?.delay && marquee?.delay > 0 ? marquee.delay : state.scroll.delay,
这里可以写成 `marquee?.delay ?? state.scroll.delay`

2022-05-18 11:59 UTC, xia7187 commented on src/notice-bar/type.ts
>    bgColor?: string;
背景颜色bgColor和文字颜色color在API里面有使用到，确定要移除吗

2022-05-18 12:16 UTC, xia7187 commented on src/notice-bar/notice-bar.vue
> +    if ((props.prefixIcon as unknown as string) !== '') {
关于prefixIcon这个属性，考虑使用“”来表示不需要图标的情况，因为theme默认是info，即无法通过theme属性来实现没有图标的功能，所以这里利用了prefixicon的优先级比theme高的情况，当传递值为空字符串的时候，即实现不需要图标的功能

2022-05-19 11:02 UTC, xia7187 commented on src/notice-bar/type.ts
>    bgColor?: string;
done

2022-05-19 11:02 UTC, xia7187 commented on src/notice-bar/type.ts
>    color?: string;
done

2022-05-19 11:02 UTC, xia7187 commented on src/notice-bar/notice-bar.vue
> +    const computedSuffixIcon = props.suffixIcon ? computed(() => renderTNode(internalInstance, 'suffixIcon')) : null;
done

2022-05-19 11:02 UTC, xia7187 commented on src/notice-bar/notice-bar.vue
> +    const showExtraText = props.extra ? computed(() => renderTNode(internalInstance, 'extra')) : null;
done

2022-05-19 11:02 UTC, xia7187 commented on src/notice-bar/notice-bar.vue
> +    if ((props.prefixIcon as unknown as string) !== '') {
done

2022-05-19 11:02 UTC, xia7187 commented on src/notice-bar/notice-bar.vue
> +      computedPrefixIcon = props.prefixIcon
done

2022-05-19 11:03 UTC, xia7187 commented on src/notice-bar/notice-bar.vue
> +  info: [h(InfoCircleFilledIcon)],
done

2022-05-19 11:03 UTC, xia7187 commented on src/notice-bar/notice-bar.vue
> +        delay: marquee?.delay && marquee?.delay > 0 ? marquee.delay : state.scroll.delay,
done

2022-05-27 08:02 UTC, merged